---
services:
  meilisearch:
    image: getmeili/meilisearch:v1.12.0-rc.5
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7702:7700
    volumes:
      - /mnt/user/appdata/meilisearch:/meili_data

  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  bar-assistant:
    image: barassistant/server:v4
    container_name: bar-assistant
    depends_on:
      meilisearch:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=false
      - PARENT_INGREDIENT_SUBSTITUTE=true
    restart: unless-stopped
    ports:
      - 8087:8080
    volumes:
      - /mnt/user/appdata/bar-assistant:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v3 
    container_name: salt-rim
    depends_on:
      bar-assistant:
        condition: service_started
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=Curfew
      - DESCRIPTION=6PM Bartender
    restart: unless-stopped
    ports:
      - 8086:8080
